'use client'

import {Accordion, AccordionItem} from "@nextui-org/react";

export default function FAQs () {
    const defaultContent =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.";

  return (
    <div className='relative'>
      <div className='absolute top-0 flex w-full justify-center'>
        <div className='left-0 h-[1px] animate-border-width rounded-full bg-gradient-to-r from-[rgba(17,17,17,0)] via-white to-[rgba(17,17,17,0)] transition-all duration-1000' />
      </div>
      <div className='flex h-full items-center justify-center rounded-md border border-gray-800 bg-gradient-to-b from-gray-950 to-black px-3 py-2'>
            <Accordion>
            <AccordionItem key="1" aria-label="How does Kyza.ai differentiate itself from other Text-to-Video SaaS platforms in terms of features and capabilities?" title="How does Kyza.ai differentiate itself from other Text-to-Video SaaS platforms in terms of features and capabilities?">
            <p className=" text-content4-foreground">
              Kyza.ai stands out through its advanced natural language processing algorithms, which enable it to generate highly accurate and contextually relevant video content. Additionally, Kyza.ai offers a wide range of customizable templates and extensive integration options, empowering users to create tailored videos effortlessly.
            </p>
            </AccordionItem>
            <AccordionItem key="2" aria-label="Can Kyza.ai accommodate specific industry requirements or niche content types?" title="Can Kyza.ai accommodate specific industry requirements or niche content types?">
            <p className=" text-content4-foreground">
              Absolutely. Kyza.ai is designed to be versatile, allowing users to input various types of content, including technical documentation, educational materials, marketing copy, and more. Our platform's adaptable algorithms ensure that the generated videos meet the specific needs and standards of diverse industries.
            </p>
            </AccordionItem>
            <AccordionItem key="3" aria-label="What level of control do users have over the visual and auditory elements of the videos generated by Kyza.ai?" title="What level of control do users have over the visual and auditory elements of the videos generated by Kyza.ai?">
            <p className=" text-content4-foreground">
              Kyza.ai provides users with extensive customization options. Users can upload custom images, logos, and voiceovers to personalise their videos. Additionally, our platform offers a user-friendly interface for adjusting visual elements such as colours, fonts, and transitions, empowering users to create videos that align with their brand identity and messaging.
            </p>
            </AccordionItem>
            <AccordionItem key="4" aria-label="How does Kyza.ai ensure the quality and accuracy of the generated videos?" title="How does Kyza.ai ensure the quality and accuracy of the generated videos?">
            <p className=" text-content4-foreground">
                Kyza.ai employs state-of-the-art AI technologies to ensure the quality and accuracy of generated videos. Our platform undergoes rigorous testing and refinement processes to optimise language processing capabilities, ensuring that the generated videos are grammatically correct, coherent, and contextually relevant. Moreover, our team continually updates and enhances our algorithms to maintain the highest standards of quality and accuracy.
            </p>
            </AccordionItem>
            <AccordionItem key="5" aria-label="Kyza.ai provide insights or analytics on video performance, such as engagement metrics or audience demographics, to help users optimise their content strategy?" title="Kyza.ai provide insights or analytics on video performance, such as engagement metrics or audience demographics, to help users optimise their content strategy?">
            <p className=" text-content4-foreground">
                Yes, Kyza.ai offers comprehensive analytics and insights to help users optimise their content strategy. Our platform provides detailed metrics on video performance, including engagement metrics such as views, likes, and shares, as well as audience demographics such as age, gender, location, and interests. These insights empower users to make data-driven decisions and refine their content strategy for maximum impact and effectiveness.
            </p>
            </AccordionItem>
            <AccordionItem key="6" aria-label="What is Kyza.ai's refund policy in case users encounter issues or are dissatisfied with the service?" title="What is Kyza.ai's refund policy in case users encounter issues or are dissatisfied with the service?">
            <p className=" text-content4-foreground">
                Kyza.ai offers a satisfaction guarantee to its users. If for any reason you are not satisfied with our service, please contact our customer support team within [insert timeframe] of your purchase, and we will work with you to address your concerns. Depending on the circumstances, we may offer a refund or alternative resolution to ensure your satisfaction.
            </p>
            </AccordionItem>
        </Accordion>
      </div>
    </div>
    
  );
}